language: node_js
node_js:
    - 'node'

script:
    - npm test
    - npm run build
after_success: npm run coverage

before_deploy: npm run pkg

deploy:
    - provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      skip_cleanup: true
      on:
          tags: true
    - provider: releases
      api_key: $GH_TOKEN
      file_glob: true
      file: pkg/*
      skip_cleanup: true
      on:
          tags: true
