on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - run: npm install

            - run: npm test

            - run: npm run build

            - run: npm run coverage

            - uses: codecov/codecov-action@v1
              with:
                  files: ./coverage.lcov

            - name: Build binary files
              if: startsWith(github.ref, 'refs/tags/')
              run: npm run pkg

            - name: Upload binary files
              if: startsWith(github.ref, 'refs/tags/')
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: pkg/linky-*
                  tag: ${{ github.ref }}
                  file_glob: true

            - name: Publish on npm
              if: startsWith(github.ref, 'refs/tags/')
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
